// An enum to represent Rust types
#[derive(Debug)]
pub enum Type {
    Bit(&'static str),
    Bool(&'static str),
    I8(&'static str),
    I16(&'static str),
    I32(&'static str),
    I64(&'static str),
    F32(&'static str),
    F64(&'static str),
    UUID(&'static str),
    Date(&'static str),
    Time(&'static str),
    Timestamp(&'static str),
    TimestampWithTz(&'static str),
    Decimal(&'static str),
    IpNetwork(&'static str),
    String(&'static str),
    Json(&'static str),
    ByteArray(&'static str),
    Unit(&'static str),
    Interval(&'static str),
    Range(Box<Type>),
    Money(&'static str),
    Tree(&'static str),
    Query(&'static str),
    Void(&'static str),
    Option(Box<Type>),
    Custom(String),
}

// Implement display for a rust:Type to visualize the mapping
impl std::fmt::Display for Type {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Type::Bit(name) => write!(f, "{}", name),
            Type::Bool(name) => write!(f, "{}", name),
            Type::I8(name) => write!(f, "{}", name),
            Type::I16(name) => write!(f, "{}", name),
            Type::I32(name) => write!(f, "{}", name),
            Type::I64(name) => write!(f, "{}", name),
            Type::F32(name) => write!(f, "{}", name),
            Type::F64(name) => write!(f, "{}", name),
            Type::UUID(name) => write!(f, "{}", name),
            Type::Date(name) => write!(f, "{}", name),
            Type::Time(name) => write!(f, "{}", name),
            Type::Timestamp(name) => write!(f, "{}", name),
            Type::TimestampWithTz(name) => write!(f, "{}", name),
            Type::Decimal(name) => write!(f, "{}", name),
            Type::IpNetwork(name) => write!(f, "{}", name),
            Type::String(name) => write!(f, "{}", name),
            Type::Json(name) => write!(f, "{}", name),
            Type::ByteArray(name) => write!(f, "{}", name),
            Type::Unit(name) => write!(f, "{}", name),
            Type::Interval(name) => write!(f, "{}", name),
            Type::Range(name) => write!(f, "{}", name),
            Type::Money(name) => write!(f, "{}", name),
            Type::Tree(name) => write!(f, "{}", name),
            Type::Query(name) => write!(f, "{}", name),
            Type::Void(name) => write!(f, "{}", name),
            Type::Option(name) => write!(f, "Option<{}>", name),
            Type::Custom(name) => write!(f, "{}", name),
        }
    }
}
